steps:
  - name: 'maven:3-jdk-11'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        cd spring-petclinic
        chmod +x mvnw
        ./mvnw clean install
        cd spring-petclinic-server
        mvn clean package docker:build

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
    - '-c'
    - |
       docker tag springboot-petclinic-actions gcr.io/$PROJECT_ID/springboot-petclinic-actions:$SHORT_SHA
       docker push gcr.io/$PROJECT_ID/springboot-petclinic-actions:$SHORT_SHA
